apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: xxl-job
  name: xxl-job
  namespace: mall
spec:
  ports:
    - nodePort: 30013
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: xxl-job
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxl-job
  namespace: mall
  labels:
    app: xxl-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxl-job
  template:
    metadata:
      labels:
        app: xxl-job
    spec:
      containers:
        - name: xxl-job
          image: xuxueli/xxl-job-admin:2.2.0
          command:
            - "sh"
            - "-c"
            - "java -jar $JAVA_OPTS /app.jar $PARAMS"
          env:
          - name: JAVA_OPT
            value: "-Xms256m -Xmx256m"
          - name: PARAMS
            value: "--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=xxl_job --spring.datasource.password=123456"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: xxl-job-logs
              mountPath: /data/applogs
      volumes:
        - name: xxl-job-logs
          persistentVolumeClaim:
            claimName: xxl-job-logs-claim
