kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: xxl-job-logs-claim
  namespace: mall
spec:
  storageClassName: nfs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
