apiVersion: v1
kind: Service
metadata:
  name: nginx-service-web01
spec:
  type: NodePort
  selector:
    app: nginx-web01
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30006  # NodePort 的范围是 30000-32767
