apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helm-nginx-repo-pvc
  namespace: helm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-sc
  resources:
    requests:
      storage: 1Gi
