apiVersion: v1
kind: Service
metadata:
  name: helm-nginx-svc
  namespace: helm
spec:
  selector:
    app: helm-repo-nginx
  type: NodePort # service类型
  ports:
  - name: http
    port: 80
    targetPort: 8080
