apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-web01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web01
  template:
    metadata:
      labels:
        app: nginx-web01
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-node01
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
